version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - xendk
  ignore:
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
    - 6.5.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  - dependency-name: lodash
    versions:
    - 4.17.20
